apiVersion: v1
kind: Secret
metadata:
  name: bookkeeping-app-secret
  namespace: bookkeeping-platform
type: Opaque
stringData:
  APP_KEY: "base64:0HSZYHuHqZKDaB4yE6v/hahdQ+5R74dbtQjW0D1qg1I="
  DB_DATABASE: "bookkeeping"
  DB_USERNAME: "bookkeeping"
  DB_PASSWORD: "bookkeeping"
  POSTGRES_DB: "bookkeeping"
  POSTGRES_USER: "bookkeeping"
  POSTGRES_PASSWORD: "bookkeeping"
  POSTGRES_REPLICATION_USER: "replicator"
  POSTGRES_REPLICATION_PASSWORD: "replicator_password"
