apiVersion: batch/v1
kind: Job
metadata:
  name: bookkeeping-seed
  namespace: bookkeeping-platform
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: ghcr.io/stankodzeparoski/book-keeping-platform-laravel/app:latest
          imagePullPolicy: Always
          args:
            - php
            - artisan
            - db:seed
            - --force
          envFrom:
            - configMapRef:
                name: bookkeeping-app-config
            - secretRef:
                name: bookkeeping-app-secret
